# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# crespo. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that crespo is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.

# include common makefile for c1 platform
$(call inherit-product-if-exists, device/samsung/c1-common/common.mk)

# apns config file
PRODUCT_COPY_FILES += \
        vendor/cyanogen/prebuilt/common/etc/apns-conf.xml:system/etc/apns-conf.xml

# These are the hardware-specific features
PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
	frameworks/base/data/etc/android.hardware.camera.flash-autofocus.xml:system/etc/permissions/android.hardware.camera.flash-autofocus.xml \
	frameworks/base/data/etc/android.hardware.camera.front.xml:system/etc/permissions/android.hardware.camera.front.xml \
	frameworks/base/data/etc/android.hardware.telephony.gsm.xml:system/etc/permissions/android.hardware.telephony.gsm.xml \
	frameworks/base/data/etc/android.hardware.location.xml:system/etc/permissions/android.hardware.location.xml \
	frameworks/base/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
	frameworks/base/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
	frameworks/base/data/etc/android.hardware.sensor.proximity.xml:system/etc/permissions/android.hardware.sensor.proximity.xml \
	frameworks/base/data/etc/android.hardware.sensor.light.xml:system/etc/permissions/android.hardware.sensor.light.xml \
	frameworks/base/data/etc/android.hardware.sensor.gyroscope.xml:system/etc/permissions/android.hardware.sensor.gyroscope.xml \
	frameworks/base/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
	frameworks/base/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
	frameworks/base/data/etc/android.software.sip.voip.xml:system/etc/permissions/android.software.sip.voip.xml \
	packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml

# Device specific apps
PRODUCT_PACKAGES += \
    SamsungServiceMode \
    C1Parts

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
	device/samsung/janice/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
	device/samsung/janice/keylayout/Broadcom_Bluetooth_HID.kl:system/usr/keylayout/Broadcom_Bluetooth_HID.kl \
	device/samsung/janice/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
	device/samsung/janice/keylayout/sec_jack.kl:system/usr/keylayout/sec_jack.kl \
	device/samsung/janice/keylayout/sec_key.kl:system/usr/keylayout/sec_key.kl \
	device/samsung/janice/keylayout/sec_touchkey.kl:system/usr/keylayout/sec_touchkey.kl

# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
    ro.opengles.version=131072

# These are the hardware-specific settings that are stored in system properties.
# Note that the only such settings should be the ones that are too low-level to
# be reachable from resources or other mechanisms.
PRODUCT_PROPERTY_OVERRIDES += \
       wifi.interface=eth0 \
       wifi.supplicant_scan_interval=20 \
       ro.telephony.ril_class=samsung \
       ro.telephony.sends_barcount=1 \
       mobiledata.interfaces=pdp0,eth0,gprs,ppp0 \
       dalvik.vm.heapsize=64m \
       persist.service.usb.setting=0 \
       dev.sfbootcomplete=0 \
       persist.sys.vold.switchexternal=1

# enable Google-specific location features,
# like NetworkLocationProvider and LocationCollector
PRODUCT_PROPERTY_OVERRIDES += \
        ro.com.google.locationfeatures=1 \
        ro.com.google.networklocation=1

# Extended JNI checks
# The extended JNI checks will cause the system to run more slowly, but they can spot a variety of nasty bugs 
# before they have a chance to cause problems.
# Default=true for development builds, set by android buildsystem.
PRODUCT_PROPERTY_OVERRIDES += \
    ro.kernel.android.checkjni=0 \
    dalvik.vm.checkjni=false
    
#MSO - 20120907 - Samsung specific props in stock build.prop
PRODUCT_PROPERTY_OVERRIDES += \
	ro.build.PDA=I9070XXLD1 \
	ro.build.hidden_ver=I9070XXLD1 \
	ro.build.changelist=1067329 \
	ro.tether.denied=false \
	ro.flash.resolution=1080 \
	ro.sf.display_rotation=0 \
	ro.factoryresetwithoutrecovery=true \
	debug.sf.hw=1 \
	ste.nmf.autoidle=1 \
	media.enable-commonsource=true \
	net.streaming.rtsp.uaprof=http://wap.samsungmobile.com/uaprof/GT-I9070.xml \
	net.streaming.rtsp.uaprof.bo=http://wap.samsungmobile.com/uaprof/GT-I9070BO.xml \
	ro.kernel.qemu=0
	
#Other Configs from stock
PRODUCT_PROPERTY_OVERRIDES += \
	ro.com.google.gmsversion=2.3_r9 /
	media.stagefright.enable-player=true /
	media.stagefright.enable-meta=false /
	media.stagefright.enable-scan=true /
	media.stagefright.enable-http=true /
	media.stagefright.enable-rtsp=true /
	dev.sfbootcomplete=0 /
	ro.secdevenc=true /
	ro.wtldatapassword=true /
	ro.com.google.clientidbase=android-samsung /
	keyguard.no_require_sim=true /
	ro.opengles.version=131072 /
	ro.error.receiver.default=com.samsung.receiver.error /
	net.bt.name=Android /
	dalvik.vm.stack-trace-file=/data/anr/traces.txt 

PRODUCT_PROPERTY_OVERRIDES += \
	ro.media.enc.jpeg.quality=100 /
	ro.media.dec.jpeg.memcap=8000000 /
	ro.media.enc.hprof.vid.bps=8000000 /
	ro.media.panorama.defres=3264x1840 /
	ro.media.panorama.frameres=1280x720 /
	ro.camcorder.videoModes=true /
	ro.media.enc.hprof.vid.fps=65 /
	media.stagefright.enable-player=true /
	media.stagefright.enable-meta=true /
	media.stagefright.enable-scan=true /
	media.stagefright.enable-http=true /
	media.stagefright.enable-rtsp=true /
	media.stagefright.enable-record=false

PRODUCT_PROPERTY_OVERRIDES += \
	debug.sf.hw=1 /
	debug.performance.tuning=1 /
	video.accelerate.hw=1 /
	debug.egl.profiler=1 /
	debug.egl.hw=1 /
	debug.composition.type=gpu /
	profiler.force_disable_err_rpt=1 /
	profiler.force_disable_ulog=1

PRODUCT_PROPERTY_OVERRIDES += \
	net.tcp.buffersize.default=4096,87380,256960,4096, 16384,256960 /
	net.tcp.buffersize.wifi=4096,87380,256960,4096,163 84,256960 /
	net.tcp.buffersize.umts=4096,87380,256960,4096,163 84,256960 /
	net.tcp.buffersize.gprs=4096,87380,256960,4096,163 84,256960 /
	net.tcp.buffersize.edge=4096,87380,256960,4096,163 84,256960 /
	ro.ril.power_collapse=1 /
	pm.sleep_mode=1 /
	wifi.supplicant_scan_interval=180 /
	ro.mot.eri.losalert.delay=1000

PRODUCT_PROPERTY_OVERRIDES += \
	ro.ril.hep=0 /
	ro.ril.hsxpa=2 /
	ro.ril.gprsclass=12 /
	ro.ril.enable.dtm=1 /
	ro.ril.hsdpa.category=8 /
	ro.ril.enable.a53=1 /
	ro.ril.enable.3g.prefix=1 /
	ro.ril.htcmaskw1.bitmask=4294967295 /
	ro.ril.htcmaskw1=14449 /
	ro.ril.hsupa.category=6 /
	ro.product.multi_touch_enabled=true /
	ro.product.max_num_touch=2 /
	persist.telephony.support.ipv6=1 /
	persist.telephony.support.ipv4=1 /
	ro.telephony.call_ring.delay=0 /
	ring.delay=0 /
	ro.lge.proximity.delay=25 /
	mot.proximity.delay=25 /
	windowsmgr.max_events_per_sec=150 /
	ro.min_pointer_dur=8 /
	ro.max.fling_velocity=12000 /
	ro.min.fling_velocity=8000 /
	persist.cust.tel.eons=1 /
	ro.config.hw_fast_dormancy=1 /
	ro.config.hw_quickpoweron=true /
	ro.kernel.android.checkjni=0 /
	ro.kernel.checkjni=0 /
	dalvik.vm.checkjni=false /
	dalvik.vm.dexopt-data-only=1 /
	dalvik.vm.heapstartsize=5m /
	dalvik.vm.heapgrowthlimit=48m /
	dalvik.vm.heapsize=64m /
	dalvik.vm.verify-bytecode=false /
	dalvik.vm.execution-mode=int:jit /
	dalvik.vm.lockprof.threshold=250 /
	dalvik.vm.dexopt-flags=m=v,o=y /
	dalvik.vm.stack-trace-file=/data/anr/traces.txt /
	dalvik.vm.jmiopts=forcecopy /
	ro.mot.buttonlight.timeout=0 /
	persist.android.strictmode=0 

# we have enough storage space to hold precise GC data
PRODUCT_TAGS += dalvik.gc.type-precise

# kernel modules for ramdisk
RAMDISK_MODULES = $(addprefix device/samsung/janice/,bthid.ko gspca_main.ko \
	scsi_wait_scan.ko Si4709_driver.ko vibrator.ko)
PRODUCT_COPY_FILES += $(foreach module,\
	$(RAMDISK_MODULES),\
	$(module):root/lib/modules/$(notdir $(module)))

# other kernel modules not in ramdisk
#~ PRODUCT_COPY_FILES += $(foreach module,\
	#~ $(filter-out $(RAMDISK_MODULES),$(wildcard device/samsung/janice/*.ko)),\
	#~ $(module):system/lib/modules/$(notdir $(module)))

# kernel modules for recovery ramdisk
#~ PRODUCT_COPY_FILES += \
    #~ device/samsung/janice/j4fs.ko:recovery/root/lib/modules/j4fs.ko

#ifeq ($(TARGET_PREBUILT_KERNEL),)
    LOCAL_KERNEL := device/samsung/janice/kernel
#else
#    LOCAL_KERNEL := $(TARGET_PREBUILT_KERNEL)
#endif

PRODUCT_COPY_FILES += \
    $(LOCAL_KERNEL):kernel

# See comment at the top of this file. This is where the other
# half of the device-specific product definition file takes care
# of the aspects that require proprietary drivers that aren't
# commonly available
$(call inherit-product-if-exists, vendor/samsung/janice/janice-vendor.mk)
